### ISSUE TITLE
Viewing page source does not work

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.gnome.Epiphany#4] opened 2018-04-09 10:52 UTC
When I click the "View page source" button, a XDG portal dialog is shown, asking which browser I want to use to view some local, generated html file. When I select _Web_, the original page is opened, but without any CSS or images. It looks like Epiphany in Flatpak is generating this garbled html file instead of the correct file containing the visualised source code.

**Comment by mcatanzaro** [comment] 2018-04-09 18:48
The problem is that the portal recognizes it's html and so shows you web browsers, but it's not going to do what you want unless you open it in a text editor like gedit instead. My first instinct was to remove the .html file extension, but that will probably fail because it's probably going to use shared-mime-info to detect the file type, so I expect it will actually open the file and notice that it's HTML regardless.

Even just getting to the point that the portal opens at all was [altogether way too much effort](https://git.gnome.org/browse/epiphany/commit/?id=5d7e8272f00fc817b29fda86aaefd928997af770).

But I'm testing it now, and I only get a blank empty file even when I do open it in gedit. Are you able to reproduce that too? Maybe something changed in xdg-desktop-portal since I hooked this up.

**Comment by mcatanzaro** [comment] 2018-04-09 18:49
What we really need is a way to override the MIME type, so we can tell the portal "hey! open this up in a text/plain handler!"

**Comment by AsciiWolf** [comment] 2018-04-09 19:04
@mcatanzaro >Are you able to reproduce that too?

Nope, but I got a "file not found" message once. I am using xdg-desktop-portal(-gtk) 0.10 on Ubuntu 18.04.

**Comment by mcatanzaro** [comment] 2018-06-01 21:14
I've restored in-browser view source mode in https://bugzilla.gnome.org/show_bug.cgi?id=738475. Should be fixed in 3.29.2-27. Closing.

**Closed by mcatanzaro** 2018-06-01 21:14 UTC

**Comment by siggi2git** [comment] 2018-06-19 15:55
that's all ?
