### ISSUE TITLE
Can't save passwords

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.Epiphany#3] opened 2018-03-20 21:03 UTC
Using Endless OS 3.3.12 I can't save passwords using Epiphany. I have Firefox account sync set up and the journal has a lot of 'Failed to store password record for xxxx timeout was reached' and 'Failed to search secrets in password secrets timeout was reached' records. I also get an "Invalid unclassed pointer in cast to 'EphyPasswordsDialog'"

It's entirely possible that this is due to a 'too old' or 'too wrong' host system in some fashion. Very happy to try and fix that.

**Comment by mcatanzaro** [comment] 2018-03-21 01:30
Hmmm, weird, definitely seems like something's going wrong in the D-Bus interaction with libsecret. Do you know if other applications using libsecret are working OK on Endless? It seems like such an unusual problem; you'd surely notice if libsecret was not generally working, because e.g. NetworkManager wouldn't be able to save Wi-Fi passwords.

I doubt this issue is related to sync. (ephy-password-manager.c lives under lib/sync due to layering reasons.) You can test to see by disabling password sync in the preferences dialog, though.

And I don't think this issue is related to Flatpak packaging, because it's working fine for me, though I use the tech preview rather than the Flathub build. We have "--talk-name=org.freedesktop.secrets" specified in the flatpak-builder json. Something could be wrong with the D-Bus filtering in flatpak, but that seems unlikely. 

The invalid cast should be easier. If you have time to grab a backtrace using G_DEBUG=fatal-criticals, that would be great.

**Comment by mcatanzaro** [comment] 2018-03-21 01:33
The only packages on the host system that would be likely to be a problem here are:

 * libsecret
 * flatpak itself

And libsecret doesn't change that much.

**Comment by TingPing** [comment] 2018-03-21 10:40
The Pithos package uses libsecret just fine.

**Comment by nedrichards** [comment] 2018-03-21 12:55
Yeah, I can't use Pithos due to geographic restrictions but Skype for example saves and restores credentials on my system.

**Comment by mcatanzaro** [comment] 2018-03-21 16:00
> The Pithos package uses libsecret just fine on my system (not EndlessOS).

We know libsecret works fine in Flatpak in general, because I've been using it for several months now.

**Comment by mcatanzaro** [comment] 2020-05-08 21:06
OK, Epiphany is back on flathub, two years later, and we have a new world order: the secrets portal.

We've intentionally not allowed access to libsecret, so password manager is guaranteed to be broken without xdg-desktop-portal 1.6. That's due to https://github.com/flatpak/xdg-desktop-portal/issues/483. Reasoning: it's better to just have a broken password manager if xdg-desktop-portal is not new enough, than for the user to save important passwords in it and see them all disappear after upgrading to xdg-desktop-portal 1.6.

**Comment by mcatanzaro** [comment] 2020-05-08 21:07
If you're able to reproduce with the new 3.36.1 build and xdg-desktop-portal 1.6 (and the non-flatpak version works), then please reopen.

**Comment by mcatanzaro** [comment] 2020-05-15 17:06
Reopening....

**Comment by mcatanzaro** [comment] 2020-05-15 17:06
> Referencing #3, I can also report that the password manager is currently not working in elementaryOS 5.1.4. (Hera). Epiphany Version is 3.36.1 (Flathub) and xdg-desktop-portal 1.6 is installed. Epiphany offers to store passwords, but there is no data shown in the settings menu.

**Comment by mcatanzaro** [comment] 2020-05-15 17:11
Works here. Somebody who can reproduce will have to debug it. I guess making sure libsecret works properly on the host system would be good, then make sure you can save secrets in other flatpak apps (e.g. Authenticator).

**Comment by Retrotux** [comment] 2020-05-15 19:01
Libsecret seems to work, there are no problems with other applications. I tried to reinstall packages in synaptic and reinstalled Epiphany from Flathub directly (not via Appcenter). Issue remains the same. Have you installed additional packages on your system that are related to password saving? I had to install an additional package (something gnome-keyring related) for the owncloud-client to work.

**Comment by mcatanzaro** [comment] 2020-05-15 19:32
Er... what exactly did you install...? The only relevant packages should be: libsecret, gnome-keyring, and xdg-desktop-portal.

I guess it's possible for Authenticator to save and remember passwords, but not Epiphany, if libsecret D-Bus API is working fine (it probably uses that) but the portal is broken (Epiphany does not have access to the D-Bus API, only the portal).

**Comment by Retrotux** [comment] 2020-05-15 21:19
The owncloud-client in the ubuntu repositiries only works when libgnome-keyring0 ist installed (see https://askubuntu.com/questions/1037978/owncloud-client-no-service-keychain-available-ubuntu-18-04). Could this be an issue? If not, is there a way to fix the portal? Manually reinstalling did not solve the problem.

**Comment by mcatanzaro** [comment] 2020-05-15 22:46
> Could this be an issue?

Of course, if you don't have gnome-keyring installed, then nothing is going to work.

> If not, is there a way to fix the portal? Manually reinstalling did not solve the problem.

We don't know what the problem is, so no, right now there's no fix. Like I said, somebody who can reproduce the issue will need to debug it.

**Comment by Retrotux** [comment] 2020-05-16 09:03
There's a misunderstanding, gnome-keyring is installed by default and I did not change that. Additionaly, I had to install libgnome-keyring0, a seperate package, to store the owncloud-password. I thought the additional package might cause a problem, but removing it did not solve the issue. So, all required packages are installed, but Epiphany does not store passwords on my system.

**Comment by mcatanzaro** [comment] 2020-05-16 14:12
> There's a misunderstanding, gnome-keyring is installed by default and I did not change that. Additionaly, I had to install libgnome-keyring0, a seperate package, to store the owncloud-password.

Looking at the Ubuntu packaging, I don't see any separate package for the library component. Are you remembering this correctly...? Anyway, libgnome-keyring is obsolete for a decade now, so I promise we are not using that. ;)

**Comment by Retrotux** [comment] 2020-05-16 14:23
Yes, 100 % sure. It is still in the 18.04 repositories. It is also recommended to install it to solve an owncloud log-in issue in Ubuntu based distributions (see https://github.com/owncloud/client/issues/6500). I totally understand that the package will not be used, I just wanted to mention it here because this could cause the problem. However, as far as I can say, this is not the case.

**Comment by mcatanzaro** [comment] 2020-05-16 15:13
So installing that is not going to have any effect whatsoever on Epiphany: can't break anything, can't fix anything either. (Unless Ubuntu has packaged it improperly, which is unlikely.) We simply don't use libgnome-keyring, so let's not worry about it.

libgnome-keyring is an obsolete alternative to libsecret. They both do basically the same thing.

**Comment by mcatanzaro** [comment] 2020-06-20 21:20
Do you see any warnings in the terminal when running `flatpak run org.gnome.Epiphany` on the command line? Anything at all to indicate what might be wrong?

**Comment by Retrotux** [comment] 2020-06-21 17:11
The following warning is shown when I start Epiphany from the command line:

Failed to load module "pantheon-filechooser-module"

**Comment by mcatanzaro** [comment] 2020-06-21 22:45
So if there are no relevant command line warnings, and I cannot reproduce, there's no path to fix this. I guess someone who can reproduce will need to rebuild Epiphany with some printfs in ephy-password-manager.c to debug what's going on.

**Comment by hadess** [comment] 2020-06-22 10:43
Are you sure the version of xdg-desktop-portal on that system is new enough to have a password portal?

**Comment by Retrotux** [comment] 2020-06-22 12:54
The xdg-desktop-portal version is 1.6.0. and is, as far as I can say, the latest one available in the bionic/elementary repositories.

**Comment by mcatanzaro** [comment] 2020-06-22 14:49
The secrets portal is present in 1.6. It should work.

**Comment by Retrotux** [comment] 2020-11-01 12:48
Failed to search secrets in password schema: org.freedesktop.DBus.Error.ServiceUnknown

That's the error message I get when I run Epiphany in the terminal.

**Comment by nedrichards** [comment] 2021-01-23 23:05
Generally unhelpful comment coming but this isn't working in Manjaro ARM on my Pinebook Pro which is, like all of Arch running pretty bleeding edge stuff but is on Endless OS 3.9.2 beta on my x86 laptop (also running fairly recent flatpak stuff). So far, so mysterious.

**Comment by mcatanzaro** [comment] 2021-12-27 14:54
OK this is a long shot, but: is it possible that you're just testing websites where Epiphany is not able to detect the password forms? That is, you're sure you can save a password on website XYZ using the non-flatpak version of Epiphany, but not the flatpak version?

Which particular website are you testing?

**Comment by mcatanzaro** [comment] 2022-02-23 15:29
>> Failed to search secrets in password schema: org.freedesktop.DBus.Error.ServiceUnknown
>
>That's the error message I get when I run Epiphany in the terminal.

This just looks like you don't have a new enough xdg-desktop-portal running.

I'm going to close this as "works for me." Feel free to reopen if you're sure the secrets portal is available and you're still unable to save secrets. If so, please run Epiphany from the command line `flatpak run org.gnome.Epiphany` and copy any warnings that you see on the command line into this bug.

**Closed by mcatanzaro** 2022-02-23 15:29 UTC
