### ISSUE TITLE
Firefox Sync feature broken by D-Bus session bus being off

### ISSUE THREAD

**Issue by JorisPLA7** [flathub/org.gnome.Epiphany#24] opened 2021-08-12 22:13 UTC
**Problem** : When connecting to Firefox sync , you get something like ` org.freedesktop.DBus.Error.ServiceUnknown`
Because of that, it's impossible to sync 
- passwords [this other issue](https://github.com/flathub/org.gnome.Epiphany/issues/3)
- bookmarks [this other issue](https://github.com/flathub/org.gnome.Epiphany/issues/16)
- tabs and so on.

**Found a fix** 
Works for me :

1. Install Flatseal `flatpak install flathub com.github.tchx84.Flatseal`
2. Run Flatseal `flatpak run com.github.tchx84.Flatseal`
3. Go to Gnome web / epiphany tab
4. Enable `D-Bus session bus` option
5. Restart Gnome web app

All done.
If I have time, I'll try to code a pull request for it to be a default option, but I honestly have no idea of how to do it now.

**Comment by mcatanzaro** [comment] 2021-08-13 19:44
Anyway, you can't allow access to the entire session bus. That defeats the point of having a sandbox. :P We need to figure out why it's failing. Can you take a screenshot of the error that you're seeing, please?

> When connecting to Firefox sync , you get something like org.freedesktop.DBus.Error.ServiceUnknown
Because of that, it's impossible to sync

Thing is, Firefox Sync shouldn't use D-Bus at all, which is why I'd like to see exactly what you're seeing.

> bookmarks this other issue

...you can't store bookmarks locally either?

**Comment by mcatanzaro** [comment] 2021-12-23 15:10
> Can you take a screenshot of the error that you're seeing, please?

**Comment by TingPing** [comment] 2021-12-23 19:16
You can run `flatpak run --log-session-bus org.gnome.Epiphany` to see exactly which service causes that error.

**Comment by fedelibre** [comment] 2022-02-23 13:01
The same error message is preventing me from printing.

```
*HIDDEN* (ping)
B-1: <- org.freedesktop.DBus return from C38
B-1: <- org.freedesktop.DBus return from C39
*REWRITTEN*

** (epiphany:2): WARNING **: 13:54:17.415: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
C40: -> org.freedesktop.DBus call org.freedesktop.DBus.GetNameOwner at /org/freedesktop/DBus

** (epiphany:2): WARNING **: 13:54:17.415: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
Filtering message due to arg0 org.freedesktop.secrets, policy: 0 (required 1)
B-1: <- org.freedesktop.DBus return from C40
*REWRITTEN*
C41: -> org.freedesktop.DBus call org.freedesktop.DBus.RemoveMatch at /org/freedesktop/DBus
B-1: <- org.freedesktop.DBus return from C41
```

**Comment by mcatanzaro** [comment] 2022-02-23 15:26
Printing is unrelated. That is not expected to work (https://bugs.webkit.org/show_bug.cgi?id=202363).

Firefox Sync is certainly expected to work. I'm going to close this bug because the reporter did not respond with the requested info. Feel free to reopen if you can provide the full error message.

**Closed by mcatanzaro** 2022-02-23 15:26 UTC

**Comment by espadrine** [comment] 2022-05-07 10:59
Hi!

I have the exact same issue as @JorisPLA7, on 42.2, also using Flatpak.

Running `flatpak run --log-session-bus org.gnome.Epiphany`, and attempting a Firefox Sync, I get this right after I enter the 2FA code:

```
C52: -> org.freedesktop.secrets call org.freedesktop.Secret.Service.OpenSession at /org/freedesktop/secrets
*HIDDEN* (ping)
B38: <- (no sender) return from C52
*REWRITTEN*

(epiphany:2): epiphany-WARNING **: 12:40:42.746: Failed to store sync secrets: org.freedesktop.DBus.Error.ServiceUnknown
```

In case it becomes relevant, my windowing environment is KDE.

**Comment by mcatanzaro** [comment] 2022-05-07 12:39
Do you have a working secrets portal? xdg-desktop-portal and gnome-keyring installed on the host system? It sure looks like https://gitlab.gnome.org/GNOME/epiphany/-/issues/1755, which was coincidentally bumped earlier today, which turned out to be a broken secrets portal caused by missing gnome-keyring. That's a host system bug, but Epiphany is not displaying a good enough error message in that case.

(FWIW the session bus is not a thing that can plausibly be off, so "Firefox Sync feature broken by D-Bus session bus being off" does not accurately describe the problem here.)

**Comment by espadrine** [comment] 2022-05-07 13:57
I have xdg-desktop-portal 1.14.1, libsecret 0.20.4, and gnome-keyring 3.36.0, all confirmed this way:

```
$ sudo apt install gnome-keyring
[…]
gnome-keyring is already the newest version (3.36.0-1ubuntu1).
$ ps aux | grep gnome-keyring
tyl        58801  0.0  0.0 237540  6900 pts/8    Sl   14:58   0:00 gnome-keyring-daemon
```

The dbus service for secrets is there, and there are some xdg-desktop-portal services:

```
$ qdbus | grep -E 'portal|secrets'
 org.freedesktop.portal.Documents
 org.freedesktop.impl.portal.PermissionStore
 org.freedesktop.portal.Desktop
 org.freedesktop.impl.portal.desktop.gtk
 org.freedesktop.impl.portal.desktop.kde
 org.freedesktop.portal.Flatpak
 org.freedesktop.secrets
```

I don’t see org.freedesktop.portal.Secret, which might be necessary?

**Comment by bilelmoussaoui** [comment] 2022-05-07 14:35
> I don’t see org.freedesktop.portal.Secret, which might be necessary?

It is part of org.freedesktop.portal.Desktop. I would assume gnome-keyring is installed but not running properly. iirc, you have to run it with gnome-keyring-daemon

**Comment by TingPing** [comment] 2022-05-07 16:36
In my testing the Secrets portal has never worked and is totally broken.

https://gitlab.gnome.org/GNOME/gnome-keyring/-/issues/61

**Comment by TingPing** [comment] 2022-05-07 16:37
If you have talk permissions to the secrets dbus api it bypasses the broken portal.

**Comment by bilelmoussaoui** [comment] 2022-05-07 17:18
> If you have talk permissions to the normal secrets dbus name it bypasses the broken portal.

Interesting, I tend to believe this is purely libsecret related as I managed to make the secret portal works fine in a re-implementation of libsecret here https://github.com/bilelmoussaoui/oo7/

**Comment by mcatanzaro** [comment] 2022-05-07 18:36
> In my testing the Secrets portal has never worked and is totally broken.

Weird, it works perfectly fine for me in Epiphany Tech Preview. I imagine we would have a huge number of complaints if it was generally not working.

> If you have talk permissions to the normal secrets dbus name it bypasses the broken portal.

No such permissions here.

> Interesting, I tend to believe this is purely libsecret related as I managed to make the secret portal works fine in a re-implementation of libsecret here https://github.com/bilelmoussaoui/oo7/

I'm curious what your plans are for this, but we can discuss that elsewhere.

**Comment by espadrine** [comment] 2022-05-11 21:08
After a recent update and restart, the behavior changed. I was able to click on Sync, and enter the password and 2FA, with no error afterwards. I am unsure whether is was successful, though, because my passwords (which are toggled on and indicated as synced) don’t autocomplete, even though I have a large number of synced passwords on the Firefox Sync account, which are indeed synced between the Firefox browser on my laptop, and the Lockwise app on my phone.

**Comment by mcatanzaro** [comment] 2022-05-12 00:09
You can check in Preferences -> Privacy -> Passwords to see if your passwords synced.

Password autocompletion is very unreliable currently. It's never going to work on every website, but we ought to be able to make it work on most. I have a list of several known failure cases and intend to investigate. If your passwords are synced but not autocompleting, feel free to report bugs in https://gitlab.gnome.org/GNOME/epiphany/-/issues, one bug per affected website.

It's also possible that the Firefox Sync feature just isn't working properly. It seems quite buggy in my experience. I'm not planning to investigate this, though: we'll need a new contributor to save the day. If your passwords failed to sync, run from the command line `flatpak run org.gnome.Epiphany` in order to catch any warnings that print, then feel free to report a bug at https://gitlab.gnome.org/GNOME/epiphany/-/issues.
